### ISSUE TITLE
Support all the Platforms that Celeste64 Supports

### ISSUE THREAD

**Issue by theofficialgman** [FujiAPI/Fuji#54]
### Please confirm the following

- [X] I have searched to ensure that my feature request is not a duplicate
- [X] My feature request will benefit the general community (i.e. it is not better off as a standalone mod)

### Describe your feature

Celeste64 supports ARM32 and ARM64 Linux and ARM64 MacOS https://github.com/ExOK/Celeste64/releases/tag/v1.1.1 that this project does not have builds for in the releases

### Why should we implement this?

Support the same platforms that the main game supports

### Optional

- [ ] I will open (or have already opened) a pull request that implements this feature.

**Comment by jasminegamedev** [comment]
I have set it up so that we should now be building for arm as of these two commits:
https://github.com/FujiAPI/Fuji/commit/befb555f193628f773d2caeb5dda5e846ad89673
https://github.com/FujiAPI/Fuji/commit/7bc2032bf2be359e93566b38fac45e96d95f6b74
There's also a test release for it here:
https://github.com/FujiAPI/Fuji/releases/tag/beta-7bc2032

Additional Disclaimer: At this point in time, I am not committing to fully supporting these platforms. I do not have access to machines to test these on and would prefer to keep focusing primarily on the Windows version for now, so these other platforms are lower priority to me, and I don't want to commit to fixing platform specific issues that pop up at this point in time. But we can try to keep it so github actions will keep building them for now at least.
